sonar.projectKey=amritbh_myPortfolio
sonar.organization=amritbh

# Source code directories
sonar.sources=src,infra/modules/backend/src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/setupTests.js,**/test_app.py

# Test directories
sonar.tests=src,infra/modules/backend/src
sonar.test.inclusions=**/*.test.js,**/test_app.py

# Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.python.coverage.reportPaths=infra/modules/backend/src/coverage.xml

# Language specific
sonar.python.version=3.9
